events {}

http {

 include /etc/nginx/mime.types;

 server {
    server_name brandnewnotes.ru;

    root /opt/public;
    index index.html;

    location /api/ {
        proxy_pass http://bnn-backend:5458;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl; # managed by Certbot
    http2 on;
    ssl_certificate /etc/letsencrypt/live/brandnewnotes.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/brandnewnotes.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
 }

 server {
    if ($host = brandnewnotes.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80 default_server;
    server_name brandnewnotes.ru;
    return 404; # managed by Certbot
 }
}