events {}
http {

 include /etc/nginx/mime.types;
 server {

  listen 80; 
  server_name brandnewnotes.ru 161.104.105.206; 

  access_log /var/log/nginx/app_access.log;
  error_log /var/log/nginx/error.log;

  location /api/ {
    proxy_pass http://bnn-backend:5458;

  }

  location / {
   root /opt/public; 
   try_files $uri $uri/ /index.html =404;
  }
 }
}
