name: Brand New Notes

on:
  push:
    branches:
      - main
      - structer-of-project

permissions:
  contents: read

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1

  linters-act:
    name: linters
    runs-on: ubuntu-latest
    needs: govulncheck
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.14.0

  tests-act:
    name: tests
    runs-on: ubuntu-latest
    needs: linters-act
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -v ./...

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: tests-act
    timeout-minutes: 30
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          command_timeout: 30m
          script_stop: true
          script: |
            cd /home/ubuntu/backend/2026_2_BNN
            git fetch origin ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            sudo docker compose up -d --build